short_takes/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('takes/', include('takes.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('search/', include('search.urls')),

    # Redirect to Builtin Login and Logout
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/short-takes-login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='auth/short-takes-logout.html'), name='logout'),
    path('accounts/register/', views.register, name='register'),

    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

takes/urls.py
from django.urls import path

from . import views

app_name = 'takes'

urlpatterns = [
    path('view/<str:take_id>', views.view, name='take'),
    path('create', views.create, name='create'),
    path('reply/<str:reply_to_id>', views.reply, name='reply'),
    path('delete/<str:take_id>', views.delete, name='delete'),

    path('like/<str:take_id>', views.like, name='up_vote'),
    path('dislike/<str:take_id>', views.dislike, name='down_vote'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('edit', views.profile_edit, name='edit'),
    path('friends/invite/<str:user_id>', views.add_friend, name='friend_add'),
    path('friends/reject/<str:user_id>', views.reject_friend, name='friend_reject'),
    path('friends/accept/<str:user_id>', views.accept_friend, name='friend_accept'),
    path('friends/remove/<str:user_id>', views.remove_friend, name='friend_remove'),
    path('friends', views.friends, name='friends'),
    path('public/<str:profile_id>', views.public_profile, name='public_profile'),
]

takes/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q


class Take(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    is_public = models.BooleanField(default=True)
    content = models.TextField(max_length=2000)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    date = models.DateTimeField(auto_now_add=True)
    reply_to = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

    liked_by = models.ManyToManyField(User, blank=True, related_name='liked_by')
    disliked_by = models.ManyToManyField(User, blank=True, related_name='disliked_by')

    def replies(self, requesting_user: User, root_author: User):
        """Loads replies for this Take, this respects visibility
        If someone replies to a Take with a private take but is not friends with the Author
        of the original Take, the Author will still be able to see the Take and all its replies
        """
        if requesting_user == root_author:
            return Take.objects.filter(reply_to__id=self.id)

        if not requesting_user.is_authenticated:
            # anonymous user can't have friends
            return Take.objects.filter(Q(reply_to__id=self.id) & Q(is_public=True))

        return Take.objects.filter(
            # is_public=False this removes duplicates, if they are friends, but it is public both would return this.
            # PEP format is crazy on this one
            (Q(reply_to__id=self.id) & (
                        Q(author__friends__from_user=requesting_user) | Q(author_id=requesting_user.id)) & Q(
                is_public=False))
            |
            (Q(reply_to__id=self.id) & Q(is_public=True))
        ).distinct()

    def reply_count(self):
        return Take.objects.filter(reply_to_id=self.id).count()

    def __str__(self):
        return f'Take={self.id}'

takes/views.py
from urllib.parse import urlencode

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm, BooleanField
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.utils.translation import gettext as _
from friendship.models import Friend

from takes.models import Take


class TakeForm(ModelForm):
    class Meta:
        model = Take
        fields = ['content', 'is_public']


class PrivateTakeForm(ModelForm):
    is_public = BooleanField(required=False, disabled=True, initial=False, help_text=_('this is a private thread'))

    class Meta:
        model = Take
        fields = ['content', 'is_public']


def view(request: HttpRequest, take_id: str) -> HttpResponse:
    take = Take.objects.get(id=take_id)

    if not take.is_public and take.author.id is not request.user.id:
        if not request.user.is_authenticated:
            # if user tries to view private take
            # redirect to login and then redirect to take again
            next_url = reverse('takes:take', kwargs={'take_id': take_id})
            login_url = reverse('login')
            redirect_url = f"{login_url}?{urlencode({'next': next_url})}"
            return HttpResponseRedirect(redirect_url)

        if not Friend.objects.are_friends(request.user, take.author):
            messages.warning(request,
                             _('This is a private Take, you are not friends with %(username)s')
                             % {'username': take.author.username})

    return render(request, 'takes-full-conversation.html', {'take': take})


@login_required
def reply(request: HttpRequest, reply_to_id: str) -> HttpResponse:
    take = Take.objects.get(id=reply_to_id)

    if take.is_public:
        form = TakeForm()
    else:
        form = PrivateTakeForm()

    if request.method == "POST":
        if take.is_public:
            form = TakeForm(request.POST)
        else:
            form = PrivateTakeForm(request.POST)

        if form.is_valid():
            take = form.save(commit=False)
            take.reply_to_id = reply_to_id
            take.author_id = request.user.id
            take.save()
            return HttpResponseRedirect(reverse('takes:take', kwargs={'take_id': reply_to_id}))

    return render(request, 'takes-reply.html', {
        'reply_form': form,
        'reply_to_take': take,
    })


@login_required
def create(request: HttpRequest) -> HttpResponse:
    form = TakeForm()

    if request.method == "POST":
        form = TakeForm(request.POST)
        if form.is_valid():
            take = form.save(commit=False)
            take.author_id = request.user.id
            take.save()
            return HttpResponseRedirect(reverse('takes:take', kwargs={'take_id': take.id}))

    return render(request, 'takes-create.html', {
        'create_form': form
    })


@login_required
def delete(request: HttpRequest, take_id: str) -> HttpResponse:
    if request.method == "POST":
        take = Take.objects.get(id=take_id)
        take.delete()
        messages.success(request, 'Take deleted')

    if request.GET.get('next', False):
        return HttpResponseRedirect(request.GET.get('next'))

    return HttpResponseRedirect(reverse('index'))


@login_required
def like(request: HttpRequest, take_id: str) -> HttpResponse:
    take = Take.objects.get(id=take_id)
    if not take.liked_by.contains(request.user):
        take.liked_by.add(request.user)
        take.disliked_by.remove(request.user)
        messages.success(request, 'You have like this take')

    if request.GET.get('next', False):
        return HttpResponseRedirect(request.GET.get('next'))

    return HttpResponseRedirect(reverse('takes:take', kwargs={'take_id': take_id}))


@login_required
def dislike(request: HttpRequest, take_id: str) -> HttpResponse:
    take = Take.objects.get(id=take_id)
    if not take.disliked_by.contains(request.user):
        take.disliked_by.add(request.user)
        take.liked_by.remove(request.user)
        messages.success(request, 'You have disliked this take')

    if request.GET.get('next', False):
        return HttpResponseRedirect(request.GET.get('next'))

    return HttpResponseRedirect(reverse('takes:take', kwargs={'take_id': take_id}))

takes/templates/takes-create.html
{% extends 'base.html' %}

{% load i18n %}
{% load my_utils %}

{% block header-left-title %}
    <h2 class="center-content">New Take</h2>
{% endblock %}

{% block content %}
    <main class="">
        <form class="center-rows" method="post" action="{% url 'takes:create' %}">
            {% csrf_token %}

            <label for="content">{% trans 'Take' %}:</label>
            {{ create_form.content }}
            {% for error in create_form.errors|extract_error_from_dict:'content' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <label for="is_public">{% trans 'Publicly visible' %}:</label>
            {{ create_form.is_public }}
            {% for error in create_form.errors|extract_error_from_dict:'is_public' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <button type="submit">{% trans 'Post your Take' %}</button>
        </form>
    </main>
{% endblock %}

takes/templates/takes-full-conversation.html
{% extends 'base.html' %}

{% block content %}
    <main class="center-rows">
        <ul> <!-- initial ul-li is needed to get a proper stacking when centering -->
            <li>
                {% include 'takes-fully-rendered.html' with take=take root_take_author=take.author %}
            </li>
        </ul>
    </main>
{% endblock %}

takes/templates/takes-fully-rendered.html
{% load my_utils %}

{% include 'takes-take.html' with take=take %}
<ul>
    {% load_allowed_replies take request.user root_take_author as replies %}
    {% for take_reply in replies %}
        <li>
             {% include 'takes-fully-rendered.html' with take=take_reply root_take_author=root_take_author %}
        </li>
    {% endfor %}
</ul>

takes/templates/takes-reply.html
{% extends 'base.html' %}

{% load i18n %}
{% load my_utils %}

{% block header-left-title %}
    <h2 class="center-content">Reply</h2>
{% endblock %}

{% block content %}
    <main class="center-rows">
        <h2>{% trans 'Reply to' %}:</h2>

        {% include 'takes-take.html' with take=reply_to_take %}
        <br />
        <form class="center-rows" method="post" action="{% url 'takes:reply' reply_to_take.id %}">
            {% csrf_token %}

            <label for="content">{% trans 'Take' %}:</label>
            {{ reply_form.content }}
            {% for error in reply_form.errors|extract_error_from_dict:'content' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <label for="is_public">{% trans 'Publicly visible' %}:</label>
            {{ reply_form.is_public }}
            {% for error in reply_form.errors|extract_error_from_dict:'is_public' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <button type="submit">{% trans 'Post your Take' %}</button>
        </form>
    </main>
{% endblock %}

takes/templates/takes-take.html
{% load my_utils %}
{% load i18n %}

<article class="take {% if not take.is_public %}private-take{% endif %}">
    <header class="take-header">
        <a class="take-profile a-as-button" href="{% url 'userprofile:public_profile' profile_id=take.author.id %}">
            <img class="profile-picture" src="{{ take.author.userprofile.avatar.url }}" alt="Avatar"/>
            {{ take.author.username }}
        </a>
        {% if request.user.id == take.author.id %}
            <form method="post" action="{% url 'takes:delete' take.id %}?next={{ request.path|urlencode }}">
                {% csrf_token %}
                <button class="stealth-button" type="submit"><i class="fa fa-trash" aria-hidden="true"></i> {% trans 'Delete' %}</button>
            </form>
        {% endif %}
    </header>

    {% if take.reply_to %}
        <div class="take-reply">
            Replied:
            <a class="a-as-button" href="{% url 'takes:take' take.reply_to.id %}">{% trans 'view original' %}</a>
        </div>
    {% endif %}

    <p class="take-content">{{ take.content }}</p>

    <p class="take-date">
        {{ take.date }}
    </p>

    <div class="take-actions">
        <div>
            {% if request.user.is_authenticated %}
                {% user_liked request.user take as liked %}
                {% user_disliked request.user take as disliked %}
            {% endif %}

            <a class="a-as-button {% if liked %}take-liked{% endif %}" href="{% url 'takes:up_vote' take.id %}?next={{ request.path|urlencode }}"><i class="fa fa-thumbs-up"></i> {{ take.liked_by.count }}</a>
            <a class="a-as-button {% if disliked %}take-disliked{% endif %}" href="{% url 'takes:down_vote' take.id %}?next={{ request.path|urlencode }}"><i class="fa fa-thumbs-down"></i> {{ take.disliked_by.count }}</a>
        </div>
        <div>
            <a class="a-as-button" href="{% url 'takes:take' take.id %}"><i class="fa fa-envelope"></i> {{ take.reply_count }} {% trans 'Full conversation' %}</a>
        </div>
        <div></div>
        <a class="a-as-button" href="{% url 'takes:reply' take.id %}"><i class="fa fa-reply"></i> {% trans 'Reply' %}</a>
    </div>
</article>