search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('simple', views.simple, name='simple'),
]

short_takes/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('takes/', include('takes.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('search/', include('search.urls')),

    # Redirect to Builtin Login and Logout
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/short-takes-login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='auth/short-takes-logout.html'), name='logout'),
    path('accounts/register/', views.register, name='register'),

    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

takes/urls.py
from django.urls import path

from . import views

app_name = 'takes'

urlpatterns = [
    path('view/<str:take_id>', views.view, name='take'),
    path('create', views.create, name='create'),
    path('reply/<str:reply_to_id>', views.reply, name='reply'),
    path('delete/<str:take_id>', views.delete, name='delete'),

    path('like/<str:take_id>', views.like, name='up_vote'),
    path('dislike/<str:take_id>', views.dislike, name='down_vote'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('edit', views.profile_edit, name='edit'),
    path('friends/invite/<str:user_id>', views.add_friend, name='friend_add'),
    path('friends/reject/<str:user_id>', views.reject_friend, name='friend_reject'),
    path('friends/accept/<str:user_id>', views.accept_friend, name='friend_accept'),
    path('friends/remove/<str:user_id>', views.remove_friend, name='friend_remove'),
    path('friends', views.friends, name='friends'),
    path('public/<str:profile_id>', views.public_profile, name='public_profile'),
]

short_takes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class EmailEnabledUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

short_takes/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from short_takes.forms import EmailEnabledUserCreationForm
from feeds.views import private_feed as priv_feed, public_feed as pub_feed


def index(request: HttpRequest) -> HttpResponse:
    current_url_parameter = request.GET.dict()
    public_feed = pub_feed(request, current_url_parameter)

    if request.user.is_authenticated:
        private_feed = priv_feed(request, current_url_parameter)  # retain all active url parameters. i.e public feed
        return render(request, 'short-takes-home.html',
                      {
                          'public_feed': public_feed.rendered_content,
                          'private_feed': None if private_feed is None else private_feed.rendered_content,
                      })

    return render(request, 'short-takes-landing.html',
                  {
                      'public_feed': public_feed.rendered_content,
                  })


def register(request: HttpRequest) -> HttpResponse:
    form = EmailEnabledUserCreationForm()

    if request.method == 'POST':
        form = EmailEnabledUserCreationForm(request.POST)
        if form.is_valid():
            user: User = form.save()
            login(request, user)

            return HttpResponseRedirect(reverse('index'))

    return render(request, 'auth/short-takes-register.html', {
        'register_form': form
    })

short_takes/templates/base.html
{% load django_htmx %}
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ShortTakes</title>

    <script src="{% static 'htmx.min.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/menu.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/takes.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/friends.css' %}"/>

    {% block additional-styles %}
    {% endblock %}

    {% django_htmx_script %}

    <style>
      @font-face {
        font-family: 'Geoplace --SC';
        src: url('{% static 'fonts/GeoplaceSC-Bold.ttf' %}') format("truetype");
      }


      @font-face {
        font-family: 'Geoplace SC';
        {#src: url('{% static 'fonts/GeoplaceSC-Bold.ttf' %}') format("truetype");#}
        src: url('{% static 'fonts/TMT-MiniMochi-SournSquishy.otf' %}') format("opentype");
        {#font-weight: bold;#}
      }
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    {% block header %}
        <header class="header-bar">
            {% block header-left-title %}
                <h2>{{ request.user.username }}</h2>
            {% endblock %}

            {% block header-center-title %}
                <a class="page-title center-content" style="grid-area: center-title;" href="/" ><h1>Short<span class="bold">Takes</span></h1></a>
            {% endblock %}

            {% block header-action %}
                {% include 'user-menu.html' %}
            {% endblock %}
        </header>
    {% endblock %}

    <hr />

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="message-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        <hr/>
    {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

short_takes/templates/short-takes-home.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="main-split">
        {{ public_feed }}

        {{ private_feed }}
    </div>

    <div class="add-take">
        <a class="a-as-button" href="{% url 'takes:create' %}"><i class="fa fa-plus-circle"></i></a>
    </div>
{% endblock %}

short_takes/templates/short-takes-landing.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="main-split">
        {{ public_feed }}

        <div class="center-content">
            <div class="center-rows">
                <h2 class="join-now">{% trans 'Join Now!' %}</h2>
                <a href="{% url 'login'%}">{% trans 'Click here to login.' %}</a>
                <a href="{% url 'register'%}">{% trans 'Click here to register.' %}</a>
            </div>
        </div>

    </div>
{% endblock %}

short_takes/templates/user-menu.html
{% load i18n %}

{% if request.user.is_authenticated %}
<div class="menu-container" style="grid-area: action">
    <form id="logout-form" action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="menu-icon" type="submit"><i class="fa fa-sign-out"></i></button>
    </form>
    <a class="menu-icon" href="{% url 'userprofile:edit' %}"><i class="fa fa-user"></i></a>
    <a class="menu-icon" href="{% url 'userprofile:friends' %}"><i class="fa fa-group"></i></a>
    <a class="menu-icon" href="{% url 'search:simple' %}"><i class="fa fa-search"></i></a>
</div>
{% endif %}