short_takes/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views, settings

urlpatterns = [
    path('', views.index, name='index'),
    path('takes/', include('takes.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('search/', include('search.urls')),

    # Redirect to Builtin Login and Logout
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='auth/short-takes-login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='auth/short-takes-logout.html'), name='logout'),
    path('accounts/register/', views.register, name='register'),

    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

takes/urls.py
from django.urls import path

from . import views

app_name = 'takes'

urlpatterns = [
    path('view/<str:take_id>', views.view, name='take'),
    path('create', views.create, name='create'),
    path('reply/<str:reply_to_id>', views.reply, name='reply'),
    path('delete/<str:take_id>', views.delete, name='delete'),

    path('like/<str:take_id>', views.like, name='up_vote'),
    path('dislike/<str:take_id>', views.dislike, name='down_vote'),
]

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('edit', views.profile_edit, name='edit'),
    path('friends/invite/<str:user_id>', views.add_friend, name='friend_add'),
    path('friends/reject/<str:user_id>', views.reject_friend, name='friend_reject'),
    path('friends/accept/<str:user_id>', views.accept_friend, name='friend_accept'),
    path('friends/remove/<str:user_id>', views.remove_friend, name='friend_remove'),
    path('friends', views.friends, name='friends'),
    path('public/<str:profile_id>', views.public_profile, name='public_profile'),
]

userprofile/models.py
from PIL import Image
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.db import models
from short_takes import settings

import os


def _safe_upload_filename(instance, filename):
    extension = ''
    split = filename.split('.')
    if len(split) > 1:
        extension = f'.{split[-1]}'
    return os.path.join(
        settings.PROFILE_IMAGES_PATH, f'{instance.user.id.__str__()}{extension}'
    )


class Userprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.ImageField(default='default-profile.png', upload_to=_safe_upload_filename)
    bio = models.TextField()

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)
        if img.height > 150 or img.width > 150:
            new_size = (150, 150)
            img.thumbnail(new_size)
            img.save(self.avatar.path)

    def __str__(self):
        return self.user.username

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Userprofile


class UpdateUserprofileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, widget=forms.FileInput())
    bio = forms.CharField(required=False, widget=forms.Textarea())

    class Meta:
        model = Userprofile
        fields = ['avatar', 'bio']


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput())
    email = forms.EmailField(required=True, widget=forms.TextInput())

    class Meta:
        model = User
        fields = ['username', 'email']

userprofile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse
from friendship.models import Friend, FriendshipRequest

from feeds.views import own_feed, create_base_feed_response
from takes.models import Take
from .forms import UpdateUserprofileForm, UpdateUserForm


def public_profile(request: HttpRequest, profile_id: str) -> HttpResponse:
    user: User = User.objects.get(pk=profile_id)

    are_friends = Friend.objects.are_friends(user, request.user)
    if are_friends:
        takes = Take.objects.filter(author=user, reply_to__isnull=True).order_by('-date')
    else:
        takes = Take.objects.filter(author=user, reply_to__isnull=True, is_public=True).order_by('-date')

    takes_list = create_base_feed_response(request, takes, 'Takes', 'take-page', None)
    takes_list.render()

    return render(request, 'userprofile-public.html',
                  {
                      'takes_list': takes_list.rendered_content,
                      'user': user,
                  })


@login_required
def add_friend(request: HttpRequest, user_id: str) -> HttpResponse:
    other_user: User = User.objects.get(pk=user_id)
    Friend.objects.add_friend(request.user, other_user)

    messages.success(request, 'Friend request send')

    return HttpResponseRedirect(reverse('userprofile:public_profile', kwargs={'profile_id': user_id}))


@login_required
def accept_friend(request: HttpRequest, user_id: str) -> HttpResponse:
    other_user: User = User.objects.get(pk=user_id)
    friend_request = FriendshipRequest.objects.get(from_user=other_user, to_user=request.user)
    friend_request.accept()

    messages.success(request, 'Friend request accepted')

    return HttpResponseRedirect(reverse('userprofile:friends'))


@login_required
def reject_friend(request: HttpRequest, user_id: str) -> HttpResponse:
    other_user: User = User.objects.get(pk=user_id)
    friend_request = FriendshipRequest.objects.get(from_user=other_user, to_user=request.user)
    friend_request.reject()

    messages.success(request, 'Friend request rejected')

    return HttpResponseRedirect(reverse('userprofile:friends'))


@login_required
def remove_friend(request: HttpRequest, user_id: str) -> HttpResponse:
    other_user: User = User.objects.get(pk=user_id)
    Friend.objects.remove_friend(request.user, other_user)

    messages.success(request, 'Friend removed')

    return HttpResponseRedirect(reverse('userprofile:friends'))


@login_required
def profile_edit(request: HttpRequest) -> HttpResponse:
    user = request.user

    own_feed_view = own_feed(request)
    own_feed_view.render()

    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=user)
        profile_form = UpdateUserprofileForm(request.POST, request.FILES, instance=user.userprofile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated.')
    else:
        user_form = UpdateUserForm(instance=user)
        profile_form = UpdateUserprofileForm(instance=user.userprofile)

    return render(request, 'userprofile-edit.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'own_feed': own_feed_view.rendered_content,
    })


@login_required
def friends(request: HttpRequest) -> HttpResponse:
    friend_requests = FriendshipRequest.objects.filter(to_user=request.user)
    friends = Friend.objects.friends(request.user)

    return render(request, 'userprofile-friends.html',
                  {
                      'friends': friends,
                      'friend_requests': friend_requests,
                  })

userprofile/templates/userprofile-edit.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load my_utils %}

{% block content %}
    <main class="main-split">
        {{ own_feed }}

        <form class="auth-form" method="post" action="{% url 'userprofile:edit' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="username">{% trans 'Username' %}:</label>
            {{ user_form.username }}
{#            <input type="text" value="{{ user.username }}" name="username" id="username"/>#}
            {% for error in user_form.errors|extract_error_from_dict:'username' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <label for="email">{% trans 'Email' %}:</label>
{#            <input type="email" value="{{ user.email }}" name="email" id="email"/>#}
            {{ user_form.email }}
            {% for error in user_form.errors|extract_error_from_dict:'email' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <img class="" src="{{ user.userprofile.avatar.url }}" alt="Avatar"/>

            <label for="avatar">{% trans 'Avatar' %}:</label>
            {{ profile_form.avatar }}
            {% for error in profile_form.errors|extract_error_from_dict:'avatar' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <label for="bio">{% trans 'Bio' %}:</label>
            {{ profile_form.bio }}
            {% for error in profile_form.errors|extract_error_from_dict:'bio' %}
                <p class="error">{{ error }}</p>
            {% endfor %}

            <button type="submit">{% trans 'Save' %}</button>
            {% for error in user_form.errors|extract_error_from_dict:'__all__' %}
                <p class="error">{{ error }}</p>
            {% endfor %}
        </form>

    </main>
{% endblock %}

userprofile/templates/userprofile-friends.html
{% extends 'base.html' %}
{% load i18n %}

{% block header-left-title %}
    <div class="center-rows-left">
        <h2>Friends</h2>
    </div>
{% endblock %}

{% block content %}

    <main class="main-split">
        <div class="center-rows">
            <h2>{% trans 'Friend Requests' %}</h2>

            {% for friend_request in friend_requests %}
                <div class="friend-request">
                    <a class="friend-request-user a-as-button" href="{% url 'userprofile:public_profile' profile_id=friend_request.from_user.id %}">
                        <img class="profile-picture" src="{{ friend_request.from_user.userprofile.avatar.url }}" alt="Avatar"/>
                        {{ friend_request.from_user.username }}
                    </a>
                    <div></div>
                    <div>
                        <a class="friend-request-button a-as-button" href="{% url 'userprofile:friend_accept' user_id=friend_request.from_user.id %}"><i class="fa fa-user-plus"></i></a>
                        <a class="friend-request-button a-as-button" href="{% url 'userprofile:friend_reject' user_id=friend_request.from_user.id %}"><i class="fa fa-user-times"></i></a>
                    </div>
                </div>

            {% empty %}
            	{% trans 'Currently no open friend requests' %}
            {% endfor %}

        </div>

        <div class="center-rows">
            <h2>{% trans 'Friends' %}</h2>
            {% for friend in friends %}
                <div class="friend-request">
                    <a class="friend-request-user a-as-button" href="{% url 'userprofile:public_profile' profile_id=friend.id %}">
                        <img class="profile-picture" src="{{ friend.userprofile.avatar.url }}" alt="Avatar"/>
                        {{ friend.username }}
                    </a>
                    <div></div>
                    <div>
                        <a class="friend-request-button a-as-button" href="{% url 'userprofile:friend_remove' user_id=friend.id %}"><i class="fa fa-user-times"></i></a>
                    </div>
                </div>

            {% empty %}
            	{% trans 'Currently no open friend requests' %}
            {% endfor %}
        </div>
    </main>
{% endblock %}

userprofile/templates/userprofile-public.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load my_utils %}

{% block header-left-title %}
    <div class="center-rows-left">
        <h2>{{ user.username }}</h2>
    </div>
{% endblock %}

{% block content %}
    <main>
        {% trans 'Bio' %}:
        <p class="profile-bio">{{ user.userprofile.bio }}</p>

        <hr/>

        {{ takes_list }}

        {% if not user.id == request.user.id %}
           {% users_are_friends request.user user as are_friends %}
            {% if not are_friends %}
                <div class="add-as-friend">
                    <a class="a-as-button" href="{% url 'userprofile:friend_add' user.id %}"><i class="fa fa-user-plus"></i></a>
                </div>
            {% endif %}
        {% endif %}
    </main>
{% endblock %}